# First of all add box to vagrant: vagrant box add packer_centos7 .\builds\virtualbox-centos7.box
Vagrant.configure("2") do |config|
  config.vm.box = "packer_centos7"
  config.vm.provider "virtualbox" do |v|
  	v.name = "packer_centos7"
        v.gui = false
  end
