
# Check source  https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.define "master" do |master|
    master.vm.box = "bento/ubuntu-16.04"
    master.vm.hostname = "master"  
    master.vm.network "private_network", ip: "192.168.50.10"
    master.vm.provision "shell" do |s|
      s.inline = <<-SHELL
      sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
      wget -qO - https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable" 
      sudo apt update -y
      sudo apt install -y docker-ce docker-ce-cli containerd.io
      sudo usermod -aG docker $USER
      sudo usermod -aG docker vagrant
      sudo swapoff -a 
      wget -qO - https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      sudo add-apt-repository "deb https://apt.kubernetes.io/ kubernetes-xenial main" 
      sudo apt update -y
      sudo apt install -y kubelet kubeadm kubectl
      sudo echo "KUBELET_EXTRA_ARGS=--node-ip=192.168.50.10" > /etc/default/kubelet
      sudo systemct  daemon_reload
      sudo systemct restart kubelet
      kubeadm init --apiserver-advertise-address="192.168.50.10" --apiserver-cert-extra-sans="192.168.50.10"  --node-name k8s-master --pod-network-cidr=192.168.0.0/16
      mkdir -p /home/vagrant/.kube
      sudo cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
      sudo chown vagrant: /home/vagrant/.kube/config
      kubectl create -f https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/calico.yaml
      kubeadm token create --print-join-command > join-command
    SHELL
      s.args = "'192.168.50.10'"
    end
    master.vm.provider "vagrant" do |v|
      v.memry = 1024
      v.cpu = 2
      v.name = "master"
      v.disksize.size = '10GB' # You need to install vagrant-disksize plugin for this
    end
  end
  (1..2).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = "bento/ubuntu-16.04"
      node.vm.hostname = "node#{i}" 
      node.vm.network "private_network", ip: "192.168.50.#{i + 10}"
      node.vm.provision "shell" do |s|
        s.inline = <<-SHELL
      sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
      wget -qO - https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable" 
      sudo apt update -y
      sudo apt install -y docker-ce docker-ce-cli containerd.io
      sudo usermod -aG docker $USER
      sudo usermod -aG docker vagrant
      sudo swapoff -a 
      wget -qO - https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      sudo add-apt-repository "deb https://apt.kubernetes.io/ kubernetes-xenial main" 
      sudo apt update -y
      sudo apt install -y kubelet kubeadm kubectl
      sudo echo "KUBELET_EXTRA_ARGS=--node-ip=$1" > /etc/default/kubelet
      sudo systemct  daemon_reload
      sudo systemct restart kubelet
      kubeadm init --apiserver-advertise-address="192.168.50.10" --apiserver-cert-extra-sans="192.168.50.10"  --node-name k8s-master --pod-network-cidr=192.168.0.0/16
    SHELL
        s.args = "'192.168.50.#{i}'"
      end
      node.vm.provider "vagrant" do |v|
        v.memry = 2048
        v.cpu = 2
        v.name = "node-#{i}"
        v.disksize.size = '15GB' # You need to install vagrant-disksize plugin for this
      end
    end
  end
end
