apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume
spec:

  accessModes: 
    - ReadWriteOnce # Volume can be mounted on read/write mode only by single node
  resources:
    requests:
      storage: 1Gi