apiVersion: apps/v1
kind: Deployment 
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template: 
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins
        volumeMounts:
          - name: jenkins-storage # name of the volume you will mount
            mountPath: /var/jenkins_home # where mount this volume
        resources:
          requests: # What we will  guaranteed to get
            memory: "512Mi"
            cpu: "500m"
          limits: # Limits that we can't exceed
            memory: "1Gi"
            cpu: "1000m"            
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000  
      restartPolicy: OnFailure
---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: jenkins-storage
spec:
  accessModes: 
    - ReadWriteOnce # the volume can be mounted as read-write by a single node
  resources: 
    requests: 
      storage: 5Gi
---
apiVersion: v1
kind: Service 
metadata:
  name: jenkins
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
  - name: jenkins
    protocol: TCP
    port: 80
    targetPort: http-port
  - name: jnlp 
    protocol: TCP
    port: 50000
    targetPort: jnlp-port

    


