apiVersion: v1
kind: Service 
metadata:
  name: grafana
spec:
  type: LoadBalancer
  selector: # Choose pods to work with
    app: grafana
  ports:
  - name: prom
    protocol: TCP
    port: 3000
    targetPort: grafana-port
  
  