apiVersion: v1
kind: Service 
metadata: 
  name: wordpress-service
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - port: 30000
      nodePort: 30000
      targetPort: http-port
      protocol: TCP

