apiVersion: apps/v1
kind: Deployment 
metadata: # Metadata for the Deployment object
  name: wordpress-deployment # Name for the Deployment object
spec: # Specification for the deployment object
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec: # Describing of the pod
      containers: 
      - name: mysql
        image: mysql:5.7
        ports: # Open port 3306
        - name: mysql-port
          containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-mysql-secr
                key: mysqldbpas
      - name: wordpress # Name of the container
        image: wordpress:4-php7.0 # Image that will be used
        ports: # Open 80 port
        - name: http-port
          containerPort: 80 
        env:
          - name: WORDPRESS_DB_PASSWORD # The same as MYSQL_ROOT_PASSWORD as this password is used to connect to mysql db
            valueFrom:
              secretKeyRef:
                name: wordpress-mysql-secr
                key: mysqldbpas
          - name: WORDPRESS_DB_HOST
            value: 127.0.0.1
