apiVersion: v1
kind: Service 
metadata:
  name: heapster-service
spec:
  type: NodePort
  selector: # Set of podsthat will use this service
    app: heapster
  ports:
    - port: 80 # within cluster
      nodePort: 30082 # on node
      targetPort: 8082 # on pod
      protocol: TCP