apiVersion: apps/v1
kind: Deployment
metadata:
  name: heapster
  labels:
    app: heapster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heapster
  template:
    metadata:
      labels:
        app: heapster
    spec:
      serviceAccountName: heapster
      containers:
        - name: heapster
          image: k8s.gcr.io/heapster-amd64:v1.5.4
          ports:
            - containerPort: 80
          command:
            - /heapster
            - --source=kubernetes:https://kubernetes.default
            - --sink=influxdb:http://influxdb-service.default.svc:8086
