apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: heapster_role
rules:
  - apiGroups: [""]
    resources: ["pods","nodes","namespaces"]
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: heapster_role
subjects:
  - kind: ServiceAccount
    name: heapster
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: heapster_role
  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: heapster

